Add available regions check for us-west1
* For all the cronjob workflows

* fix env

* fix env

* fix env

* Prepare non-europe region

* Use list of available regions

* Add custom validation for regions depending on variable

diff --git a/.github/workflows/cron_manual-deploy.yml b/.github/workflows/cron_manual-deploy.yml
--- a/.github/workflows/cron_manual-deploy.yml
+++ b/.github/workflows/cron_manual-deploy.yml
@@ -32,6 +32,11 @@ on:
           type: string
           default: "#plt-239"
           description: "Slack channel ID where you want your notifications"
+        region:
+          required: false
+          type: string
+          description: "Region name to deploy - europe or us-central1, defaults to europe"
+          default: "europe"
 
 
 env:
@@ -46,6 +51,8 @@ env:
   GAR_ENABLED: ${{ vars.GAR_ENABLED || 'true' }}
   GCR_DEFAULT_REPO: ${{ vars.GCR_DEFAULT_REPO }}
   GAR_DEFAULT_REPO: ${{ vars.GAR_DEFAULT_REPO }}
+  REGION: ${{ inputs.region }}
+  AVAILABLE_ZONES_FOR_DEPLOYMENT: ${{ vars.AVAILABLE_ZONES_FOR_DEPLOYMENT }}
 
 jobs:
   deploy:
@@ -58,6 +65,16 @@ jobs:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
+      
+      - name: Check if region is valid
+        run: |-
+          if [[ " ${AVAILABLE_ZONES_FOR_DEPLOYMENT[*]} " =~ ${{ env.REGION }} ]]; then
+            echo "This region - ${{ env.REGION }} - is allowed"
+          else
+            echo "Region - ${{ env.REGION }} - is not yet supported. Supported regions are: ${AVAILABLE_ZONES_FOR_DEPLOYMENT[*]}"
+            echo "::error::Region - ${{ env.REGION }} - is not yet supported. Supported regions are: ${AVAILABLE_ZONES_FOR_DEPLOYMENT[*]}"
+            exit 1
+          fi
 
       - id: "image_name"
         name: "Extract repo name and update IMAGE_NAME"
@@ -94,7 +111,8 @@ jobs:
           echo "gar_image_name=$GAR_IMAGE_NAME" >> $GITHUB_OUTPUT
           echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
 
-      - name: Get env file and scheduler for updating k8s-manifest repo
+      - name: Get env file and scheduler for updating k8s-manifest repo in case of europe region
+        if: ${{ env.REGION == 'europe' }}
         run: |-
           if [[ "${ENVIRONMENT}" = "production" ]]; then
             cat "deployment_envs/prod.env" > $HOME/envfile.env
@@ -108,6 +126,23 @@ jobs:
           fi
           if [[ -f "deployment_envs/common.env" ]]; then
             echo "Please delete deployment_envs/common.env" >> $GITHUB_STEP_SUMMARY
+          fi
+      
+      - name: Get env file and scheduler for updating k8s-manifest repo in case of us region
+        if: ${{ env.REGION != 'europe' }}
+        run: |-
+          if [[ "${ENVIRONMENT}" = "production" ]]; then
+            cat "deployment_envs/region/${{ env.REGION }}/prod.env" > $HOME/envfile.env
+            cat "deployment_schedules/region/${{ env.REGION }}/prod" > $HOME/scheduler
+          elif [[ "${ENVIRONMENT}" = "staging" ]]; then
+            cat "deployment_envs/region/${{ env.REGION }}/stage.env" > $HOME/envfile.env
+            cat "deployment_schedules/region/${{ env.REGION }}/stage" > $HOME/scheduler
+          else
+            cat "deployment_envs/region/${{ env.REGION }}/dev.env" > $HOME/envfile.env
+            cat "deployment_schedules/region/${{ env.REGION }}/dev" > $HOME/scheduler
+          fi
+          if [[ -f "deployment_envs/region/${{ env.REGION }}/common.env" ]]; then
+            echo "Please delete deployment_envs/region/${{ env.REGION }}/common.env" >> $GITHUB_STEP_SUMMARY
           fi
 
       - id: fetch_latest_release
@@ -170,8 +205,28 @@ jobs:
           echo "changelog_json=$JSON_CONTENT" >> $GITHUB_OUTPUT
 
       - name: Update the Image tags and env files for Selected Environment
+        if: ${{ env.REGION == 'europe' }}
         run: |-
           cd $APP_SQUAD/${{ github.event.repository.name }}/overlay/$ENVIRONMENT
+          FILE_ENV=$(ls | grep ".env");cat $HOME/envfile.env > $FILE_ENV
+          ls $HOME
+          scheduler=$(cat $HOME/scheduler)
+          yq ".spec.schedule = \"$scheduler\"" -i cronjob.yaml
+          kustomize edit set image app=${IMAGE_NAME}:${TAGS}
+          cat kustomization.yaml
+          git config --local user.email $GITHUB_EMAIL
+          git config --local user.name $GITHUB_USER
+          git commit -m "update image to ${IMAGE_NAME}:${TAGS}" -a || echo "Nothing to commit, version ${TAGS} is already deployed to $ENVIRONMENT" >> $GITHUB_STEP_SUMMARY
+          git push ${REMOTE_REPO} HEAD:main --force
+        env:
+          TAGS: ${{ steps.tag_to_deploy.outputs.tag }}
+          REMOTE_REPO: https://${{ secrets.ULTIMATE_GITHUB_PAT }}@github.com/${{ env.K8S_MANIFESTS_REPO }}.git
+          IMAGE_NAME: ${{ steps.image_name.outputs.image_name }}
+      
+      - name: Update the Image tags and env files for Selected Environment
+        if: ${{ env.REGION != 'europe' }}
+        run: |-
+          cd $APP_SQUAD/${{ github.event.repository.name }}/region/${REGION}/$ENVIRONMENT
           FILE_ENV=$(ls | grep ".env");cat $HOME/envfile.env > $FILE_ENV
           scheduler=$(cat $HOME/scheduler)
           yq ".spec.schedule = \"$scheduler\"" -i cronjob.yaml
diff --git a/.github/workflows/cron_merged-pr.yml b/.github/workflows/cron_merged-pr.yml
--- a/.github/workflows/cron_merged-pr.yml
+++ b/.github/workflows/cron_merged-pr.yml
@@ -70,6 +70,11 @@ on:
           required: false
           type: string
           description: "Npm version used in the pipeline, defaults to LTS version"
+        region:
+          required: false
+          type: string
+          description: "Region name to deploy - europe or us-central1, defaults to europe"
+          default: "europe"
 
 
 env:
@@ -92,6 +97,8 @@ env:
   GAR_ENABLED: ${{ vars.GAR_ENABLED || 'true' }}
   GCR_DEFAULT_REPO: ${{ vars.GCR_DEFAULT_REPO }}
   GAR_DEFAULT_REPO: ${{ vars.GAR_DEFAULT_REPO }}
+  REGION: ${{ inputs.region }}
+  AVAILABLE_ZONES_FOR_DEPLOYMENT: ${{ vars.AVAILABLE_ZONES_FOR_DEPLOYMENT }}
 
 jobs:
   bump-release:
@@ -166,6 +173,16 @@ jobs:
         run: |
           echo "At least one of GCR_ENABLED or GAR_ENABLED must be set to true.'
           exit 1
+      
+      - name: Check if region is valid
+        run: |-
+          if [[ " ${AVAILABLE_ZONES_FOR_DEPLOYMENT[*]} " =~ ${{ env.REGION }} ]]; then
+            echo "This region - ${{ env.REGION }} - is allowed"
+          else
+            echo "Region - ${{ env.REGION }} - is not yet supported. Supported regions are: ${AVAILABLE_ZONES_FOR_DEPLOYMENT[*]}"
+            echo "::error::Region - ${{ env.REGION }} - is not yet supported. Supported regions are: ${AVAILABLE_ZONES_FOR_DEPLOYMENT[*]}"
+            exit 1
+          fi
 
       - uses: actions/checkout@v4
         with:
@@ -216,7 +233,8 @@ jobs:
           echo "gar_image_name=$GAR_IMAGE_NAME" >> $GITHUB_OUTPUT
           echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
 
-      - name: Get environment.env file and scheduler for updating k8s-manifest repo
+      - name: Get environment.env file and scheduler for updating k8s-manifest repo in europe region scenario
+        if: ${{ env.REGION == 'europe' }}
         run: |-
           if [[ "${AUTOMATIC_DEPLOYMENT_TO}" == *"staging"* ]]; then
             cat "deployment_envs/stage.env" > $HOME/staging-envfile.env
@@ -228,6 +246,21 @@ jobs:
           fi
           if [[ -f "deployment_envs/common.env" ]]; then
             echo "Please delete deployment_envs/common.env" >> $GITHUB_STEP_SUMMARY
+          fi
+
+      - name: Get environment.env file and scheduler for updating k8s-manifest repo in us region scenario
+        if: ${{ env.REGION != 'europe' }}
+        run: |-
+          if [[ "${AUTOMATIC_DEPLOYMENT_TO}" == *"staging"* ]]; then
+            cat "deployment_envs/region/${{ env.REGION }}/stage.env" > $HOME/staging-envfile.env
+            cat "deployment_schedules/region/${{ env.REGION }}/stage" > $HOME/staging-scheduler
+          fi
+          if [[ "${AUTOMATIC_DEPLOYMENT_TO}" == *"development"* ]]; then
+            cat "deployment_envs/region/${{ env.REGION }}/dev.env" > $HOME/development-envfile.env
+            cat "deployment_schedules/region/${{ env.REGION }}/dev" > $HOME/development-scheduler
+          fi
+          if [[ -f "deployment_envs/region/${{ env.REGION }}/common.env" ]]; then
+            echo "Please delete deployment_envs/region/${{ env.REGION }}/common.env" >> $GITHUB_STEP_SUMMARY
           fi
 
       - id: fetch_latest_release
@@ -314,7 +347,8 @@ jobs:
           repository: ${{ env.K8S_MANIFESTS_REPO }}
           token: ${{ secrets.ULTIMATE_GITHUB_PAT }}
 
-      - name: Update the Image tags for Preproduction Environment
+      - name: Update the Image tags for Preproduction Environment for europe region
+        if: ${{ env.REGION == 'europe' }}
         run: |-
           if [[ $K8S_ENV_NAME == *","* ]]; then
             echo "Deploying in multiple environments: $K8S_ENV_NAME"
@@ -342,6 +376,55 @@ jobs:
           else
             if [[ "${K8S_ENV_NAME}" == "development" || "${K8S_ENV_NAME}" == "staging"  ]]; then
               cd $APP_SQUAD/${{ github.event.repository.name }}/overlay/${K8S_ENV_NAME}
+              FILE_ENV=$(ls | grep ".env");cat $HOME/${K8S_ENV_NAME}-envfile.env > $FILE_ENV
+              kustomize edit set image app=${IMAGE_NAME}:${TAGS}
+              cat kustomization.yaml
+              scheduler=$(cat $HOME/${K8S_ENV_NAME}-scheduler)
+              yq ".spec.schedule = \"$scheduler\"" -i cronjob.yaml
+              git config --local user.email $GITHUB_EMAIL
+              git config --local user.name $GITHUB_USER
+              git commit -m "update image to ${IMAGE_NAME}:${TAGS}" -a || echo "Nothing to commit, version ${IMAGE_NAME}:${TAGS} is already deployed to ${K8S_ENV_NAME}" >> $GITHUB_STEP_SUMMARY
+              git push ${REMOTE_REPO} HEAD:main --force
+            else
+              echo "You want to deploy automatically to ${K8S_ENV_NAME}, which is not development nor staging. This is not allowed."
+              exit 1
+            fi
+          fi
+        env:
+          TAGS: ${{ steps.fetch_latest_release.outputs.tag_name }}
+          REMOTE_REPO: https://${{ secrets.ULTIMATE_GITHUB_PAT }}@github.com/${{ env.K8S_MANIFESTS_REPO }}.git
+          K8S_ENV_NAME: ${{ env.AUTOMATIC_DEPLOYMENT_TO }}
+          IMAGE_NAME: ${{ steps.image_name.outputs.image_name }}
+
+    - name: Update the Image tags for Preproduction Environment for US region
+        if: ${{ env.REGION != 'europe' }}
+        run: |-
+          if [[ $K8S_ENV_NAME == *","* ]]; then
+            echo "Deploying in multiple environments: $K8S_ENV_NAME"
+            IFS=',' read -r -a envs <<< "$K8S_ENV_NAME"
+            for env in "${envs[@]}"
+            do
+              if [[ $env == "development" || $env == "staging"  ]]; then
+                  echo "Deploying ${{ github.event.repository.name }} at $env "
+                  cd $APP_SQUAD/${{ github.event.repository.name }}/region/${REGION}/$env
+                  FILE_ENV=$(ls | grep ".env");cat $HOME/$env-envfile.env > $FILE_ENV
+                  kustomize edit set image app=${IMAGE_NAME}:${TAGS}
+                  scheduler=$(cat $HOME/$env-scheduler)
+                  yq ".spec.schedule = \"$scheduler\"" -i cronjob.yaml
+                  cat kustomization.yaml
+                  git config --local user.email $GITHUB_EMAIL
+                  git config --local user.name $GITHUB_USER
+                  git commit -m "update $env image to ${IMAGE_NAME}:${TAGS}" -a || echo "Nothing to commit, version ${IMAGE_NAME}:${TAGS} is already deployed to $env" >> $GITHUB_STEP_SUMMARY
+                  git push ${REMOTE_REPO} HEAD:main --force
+                  cd ../../../../
+              else
+                echo "You want to deploy automatically to $env, which is not development nor staging. This is not allowed."
+                exit 1
+              fi
+            done
+          else
+            if [[ "${K8S_ENV_NAME}" == "development" || "${K8S_ENV_NAME}" == "staging"  ]]; then
+              cd $APP_SQUAD/${{ github.event.repository.name }}/region/${REGION}/${K8S_ENV_NAME}
               FILE_ENV=$(ls | grep ".env");cat $HOME/${K8S_ENV_NAME}-envfile.env > $FILE_ENV
               kustomize edit set image app=${IMAGE_NAME}:${TAGS}
               cat kustomization.yaml
diff --git a/.github/workflows/cron_rollback.yml b/.github/workflows/cron_rollback.yml
--- a/.github/workflows/cron_rollback.yml
+++ b/.github/workflows/cron_rollback.yml
@@ -36,6 +36,11 @@ on:
           type: string
           default: "#plt-239"
           description: "Slack channel ID where you want your notifications"
+        region:
+          required: false
+          type: string
+          description: "Region name to deploy - europe or us-central1, defaults to europe"
+          default: "europe"
 
 
 env:
@@ -51,6 +56,8 @@ env:
   GAR_ENABLED: ${{ vars.GAR_ENABLED || 'true' }}
   GCR_DEFAULT_REPO: ${{ vars.GCR_DEFAULT_REPO }}
   GAR_DEFAULT_REPO: ${{ vars.GAR_DEFAULT_REPO }}
+  REGION: ${{ inputs.region }}
+  AVAILABLE_ZONES_FOR_DEPLOYMENT: ${{ vars.AVAILABLE_ZONES_FOR_DEPLOYMENT }}
 
 jobs:
   deploy_rollback:
@@ -64,6 +71,16 @@ jobs:
         with:
           fetch-depth: 0
           ref: ${{ inputs.version }}
+      
+      - name: Check if region is valid
+        run: |-
+          if [[ " ${AVAILABLE_ZONES_FOR_DEPLOYMENT[*]} " =~ ${{ env.REGION }} ]]; then
+            echo "This region - ${{ env.REGION }} - is allowed"
+          else
+            echo "Region - ${{ env.REGION }} - is not yet supported. Supported regions are: ${AVAILABLE_ZONES_FOR_DEPLOYMENT[*]}"
+            echo "::error::Region - ${{ env.REGION }} - is not yet supported. Supported regions are: ${AVAILABLE_ZONES_FOR_DEPLOYMENT[*]}"
+            exit 1
+          fi
 
       - id: "image_name"
         name: "Extract repo name and update IMAGE_NAME"
@@ -111,7 +128,8 @@ jobs:
           TAG=$VERSION
           echo '::set-output name=tag::'$TAG
 
-      - name: Get environment.env file for updating k8s-manifest repo
+      - name: Get environment.env file for updating k8s-manifest repo for europe region
+        if: ${{ env.REGION == 'europe' }}
         run: |-
           if [[ "${ENVIRONMENT}" = "production" ]]; then
             cat "deployment_envs/prod.env" > $HOME/envfile.env
@@ -125,6 +143,23 @@ jobs:
           fi
           if [[ -f "deployment_envs/common.env" ]]; then
             echo "Please delete deployment_envs/common.env" >> $GITHUB_STEP_SUMMARY
+          fi
+      
+      - name: Get environment.env file for updating k8s-manifest repo for us region
+        if: ${{ env.REGION != 'europe' }}
+        run: |-
+          if [[ "${ENVIRONMENT}" = "production" ]]; then
+            cat "deployment_envs/region/${{ env.REGION }}/prod.env" > $HOME/envfile.env
+            cat "deployment_schedules/region/${{ env.REGION }}/prod" > $HOME/scheduler
+          elif [[ "${ENVIRONMENT}" = "staging" ]]; then
+            cat "deployment_envs/region/${{ env.REGION }}/stage.env" > $HOME/envfile.env
+            cat "deployment_schedules/region/${{ env.REGION }}/stage" > $HOME/scheduler
+          else
+            cat "deployment_envs/region/${{ env.REGION }}/dev.env" > $HOME/envfile.env
+            cat "deployment_schedules/region/${{ env.REGION }}/dev" > $HOME/cheduler
+          fi
+          if [[ -f "deployment_envs/region/${{ env.REGION }}/common.env" ]]; then
+            echo "Please delete deployment_envs/region/${{ env.REGION }}/common.env" >> $GITHUB_STEP_SUMMARY
           fi
 
       - name: "Checkout k8s manifests"
@@ -153,9 +188,28 @@ jobs:
         env:
           TAGS: ${{ steps.tag_to_deploy.outputs.tag }}
 
-      - name: Update the Image tags for Selected Environment
+      - name: Update the Image tags for Selected Environment for Europe region
+        if: ${{ env.REGION == 'europe' }}
         run: |-
           cd $APP_SQUAD/${{ github.event.repository.name }}/overlay/$ENVIRONMENT
+          FILE_ENV=$(ls | grep ".env");cat $HOME/envfile.env > $FILE_ENV
+          kustomize edit set image app=${IMAGE_NAME}:${TAGS}
+          scheduler=$(cat $HOME/scheduler)
+          yq ".spec.schedule = \"$scheduler\"" -i cronjob.yaml
+          cat kustomization.yaml
+          git config --local user.email $GITHUB_EMAIL
+          git config --local user.name $GITHUB_USER
+          git commit -m "update image to ${IMAGE_NAME}:${TAGS}" -a || echo "Nothing to commit, version ${TAGS} is already deployed to $ENVIRONMENT" >> $GITHUB_STEP_SUMMARY
+          git push ${REMOTE_REPO} HEAD:main --force
+        env:
+          TAGS: ${{ steps.tag_to_deploy.outputs.tag }}
+          REMOTE_REPO: https://${{ secrets.ULTIMATE_GITHUB_PAT }}@github.com/${{ env.K8S_MANIFESTS_REPO }}.git
+          IMAGE_NAME: ${{ steps.image_name.outputs.image_name }}
+      
+      - name: Update the Image tags for Selected Environment for non europe region
+        if: ${{ env.REGION != 'europe' }}
+        run: |-
+          cd $APP_SQUAD/${{ github.event.repository.name }}/region/${REGION}/$ENVIRONMENT
           FILE_ENV=$(ls | grep ".env");cat $HOME/envfile.env > $FILE_ENV
           kustomize edit set image app=${IMAGE_NAME}:${TAGS}
           scheduler=$(cat $HOME/scheduler)
diff --git a/.github/workflows/rollback.yml b/.github/workflows/rollback.yml
--- a/.github/workflows/rollback.yml
+++ b/.github/workflows/rollback.yml
@@ -44,6 +44,11 @@ on:
           type: string
           default: "#plt-239"
           description: "Slack channel ID where you want your notifications"
+        region:
+          required: false
+          type: string
+          description: "Region name to deploy - europe or us-central1, defaults to europe"
+          default: "europe"
 
 
 env:
@@ -61,6 +66,8 @@ env:
   GAR_ENABLED: ${{ vars.GAR_ENABLED || 'true' }}
   GCR_DEFAULT_REPO: ${{ vars.GCR_DEFAULT_REPO }}
   GAR_DEFAULT_REPO: ${{ vars.GAR_DEFAULT_REPO }}
+  REGION: ${{ inputs.region }}
+  AVAILABLE_ZONES_FOR_DEPLOYMENT: ${{ vars.AVAILABLE_ZONES_FOR_DEPLOYMENT }}
 
 jobs:
   deploy_rollback:
@@ -74,6 +81,16 @@ jobs:
         with:
           fetch-depth: 0
           ref: ${{ inputs.version }}
+      
+      - name: Check if region is valid
+        run: |-
+          if [[ " ${AVAILABLE_ZONES_FOR_DEPLOYMENT[*]} " =~ ${{ env.REGION }} ]]; then
+            echo "This region - ${{ env.REGION }} - is allowed"
+          else
+            echo "Region - ${{ env.REGION }} - is not yet supported. Supported regions are: ${AVAILABLE_ZONES_FOR_DEPLOYMENT[*]}"
+            echo "::error::Region - ${{ env.REGION }} - is not yet supported. Supported regions are: ${AVAILABLE_ZONES_FOR_DEPLOYMENT[*]}"
+            exit 1
+          fi
 
       - id: "image_name"
         name: "Extract repo name and update IMAGE_NAME"
@@ -132,28 +149,8 @@ jobs:
           fi
           echo "app_names=$APP_NAMES" >> $GITHUB_OUTPUT
 
-      # - id: tag_to_deploy
-      #   name: Calculate version to deploy
-      #   run: |-
-      #     if [[ -z "${VERSION}"  ]]; then
-      #       echo "Version is empty, in rollback workflow version is mandatory!"
-      #       exit 1
-      #     else
-      #       if [[ -z "${ALLOWED_USERS}"  ]]; then
-      #         echo "You have selected a specific version to deploy, but provided no list of people who can deploy specific versions (allowed_users)"
-      #         exit 1
-      #       fi
-      #       IFS=',' read -r -a array <<< "$ALLOWED_USERS"
-      #       if [[ " ${array[*]} " =~ ${{ github.actor }} ]]; then
-      #         echo "This user - ${{ github.actor }} - is allowed"
-      #         TAG=$VERSION
-      #       else
-      #         echo "Sorry,${{ github.actor }}, you are not allowed to choose specific version to deploy - contact your platform team"
-      #         exit 1
-      #       fi
-      #     fi
-      #     echo '::set-output name=tag::'$TAG
-      - name: Get environment.env file for updating k8s-manifest repo
+      - name: Get environment.env file for updating k8s-manifest repo in europe region scenario
+        if: ${{ env.REGION == 'europe' }}
         run: |-
           if [[ $APP_NAMES == *","* ]]; then
               IFS=',' read -r -a array_app_names <<< "$APP_NAMES"
@@ -180,6 +177,37 @@ jobs:
             fi
             if [[ -f "deployment_envs/common.env" ]]; then
               echo "Please delete deployment_envs/common.env" >> $GITHUB_STEP_SUMMARY
+            fi
+          fi
+
+      - name: Get environment.env file for updating k8s-manifest repo in non-europe region scenario
+        if: ${{ env.REGION != 'europe' }}
+        run: |-
+          if [[ $APP_NAMES == *","* ]]; then
+              IFS=',' read -r -a array_app_names <<< "$APP_NAMES"
+              for app_name in "${array_app_names[@]}"
+              do
+                if [[ "${ENVIRONMENT}" = "production" ]]; then
+                  cat "deployment_envs/$app_name/region/$REGION/prod.env" > $HOME/$app_name-envfile.env
+                elif [[ "${ENVIRONMENT}" = "staging" ]]; then
+                  cat "deployment_envs/$app_name/region/$REGION/stage.env" > $HOME/$app_name-envfile.env
+                else
+                  cat "deployment_envs/$app_name/region/$REGION/dev.env" > $HOME/$app_name-envfile.env
+                fi
+                if [[ -f "deployment_envs/$app_name/region/$REGION/common.env" ]]; then
+                  echo "Please delete deployment_envs/$app_name/region/$REGION/common.env" >> $GITHUB_STEP_SUMMARY
+                fi
+              done
+          else
+            if [[ "${ENVIRONMENT}" = "production" ]]; then
+              cat "deployment_envs/region/$REGION/prod.env" > $HOME/envfile.env
+            elif [[ "${ENVIRONMENT}" = "staging" ]]; then
+              cat "deployment_envs/region/$REGION/stage.env" > $HOME/envfile.env
+            else
+              cat "deployment_envs/region/$REGION/dev.env" > $HOME/envfile.env
+            fi
+            if [[ -f "deployment_envs/region/$REGION/common.env" ]]; then
+              echo "Please delete deployment_envs/region/$REGION/common.env" >> $GITHUB_STEP_SUMMARY
             fi
           fi
 
@@ -225,7 +253,8 @@ jobs:
           TAGS: ${{ steps.tag_to_deploy.outputs.tag }}
           SINGLE_APP_NAME: ${{ steps.app_names.outputs.single_app_name }}
 
-      - name: Update the Image tags for Selected Environment
+      - name: Update the Image tags for Selected Environment in case of europe region
+        if: ${{ env.REGION == 'europe' }}
         run: |-
           if [[ $APP_NAMES == *","* ]]; then
             IFS=',' read -r -a array_app_names <<< "$APP_NAMES"
@@ -261,6 +290,45 @@ jobs:
           IMAGE_NAME: ${{ steps.image_name.outputs.image_name }}
           APP_NAMES: ${{ steps.app_names.outputs.app_names }}
           SINGLE_APP_NAME: ${{ steps.app_names.outputs.single_app_name }}
+
+      - name: Update the Image tags for Selected Environment in case of non-europe region
+        if: ${{ env.REGION != 'europe' }}
+        run: |-
+          if [[ $APP_NAMES == *","* ]]; then
+            IFS=',' read -r -a array_app_names <<< "$APP_NAMES"
+            for app_name in "${array_app_names[@]}"
+            do
+              cd $APP_SQUAD/$app_name/region/$REGION/$ENVIRONMENT
+              FILE_ENV=$(ls | grep ".env");cat $HOME/$app_name-envfile.env > $FILE_ENV
+              kustomize edit set image app=${IMAGE_NAME}:${TAGS}
+              cat kustomization.yaml
+              git config --local user.email $GITHUB_EMAIL
+              git config --local user.name $GITHUB_USER
+              git commit -m "update $app_name image to ${IMAGE_NAME}:${TAGS}" -a || echo "Nothing to commit, $app_name version ${TAGS} is already deployed to $ENVIRONMENT" >> $GITHUB_STEP_SUMMARY
+              git push ${REMOTE_REPO} HEAD:main --force
+              cd ../../../../
+            done
+          else
+            if [[ "${SINGLE_APP_NAME}" ]]; then
+              cd $APP_SQUAD/$SINGLE_APP_NAME/region/$REGION/$ENVIRONMENT
+            else
+              cd $APP_SQUAD/${APP_NAMES}/region/$REGION/$ENVIRONMENT
+            fi
+            FILE_ENV=$(ls | grep ".env");cat $HOME/envfile.env > $FILE_ENV
+            kustomize edit set image app=${IMAGE_NAME}:${TAGS}
+            cat kustomization.yaml
+            git config --local user.email $GITHUB_EMAIL
+            git config --local user.name $GITHUB_USER
+            git commit -m "update image to ${IMAGE_NAME}:${TAGS}" -a || echo "Nothing to commit, version ${TAGS} is already deployed to $ENVIRONMENT" >> $GITHUB_STEP_SUMMARY
+            git push ${REMOTE_REPO} HEAD:main --force
+          fi
+        env:
+          TAGS: ${{ steps.tag_to_deploy.outputs.tag }}
+          REMOTE_REPO: https://${{ secrets.ULTIMATE_GITHUB_PAT }}@github.com/${{ env.K8S_MANIFESTS_REPO }}.git
+          IMAGE_NAME: ${{ steps.image_name.outputs.image_name }}
+          APP_NAMES: ${{ steps.app_names.outputs.app_names }}
+          SINGLE_APP_NAME: ${{ steps.app_names.outputs.single_app_name }}
+
 
       - uses: slackapi/slack-github-action@v1.24.0
         name: Slack notification
