First attempt

diff --git a/.github/workflows/manual-deploy.yml b/.github/workflows/manual-deploy.yml
--- a/.github/workflows/manual-deploy.yml
+++ b/.github/workflows/manual-deploy.yml
@@ -97,6 +97,7 @@ jobs:
       deployment_name: ${{ steps.gather_data.outputs.deployment_name }}
       environment: ${{ env.ENVIRONMENT}}
       run_e2e_tests: ${{ env.RUN_E2E_TESTS}}
+      thread_ts: ${{ steps.slack_notif.outputs.thread_ts }}
     permissions:
       contents: "read"
       id-token: "write"
@@ -165,6 +166,7 @@ jobs:
         run: |-
           CHANGELOG_LINES=$(head -4 CHANGELOG.md)
           echo '::set-output name=changelog_lines::'$CHANGELOG_LINES
+          echo "changelog_lines=$CHANGELOG_LINES" >> $GITHUB_ENV
 
       - name: "Checkout k8s manifests"
         uses: actions/checkout@v3
@@ -283,12 +285,6 @@ jobs:
           RELEASE_TITLE: ${{ steps.fetch_latest_release.outputs.name }}
           CHANGELOG_LINES: ${{ steps.get_changelog_content.outputs.changelog_lines }}
       
-      - name: Run tests
-        run: |-
-          echo "Slack message outputs"
-          echo "Ts --> " ${{ steps.slack_notif.outputs.ts }}
-          echo "time --> ${{ steps.slack_notif.outputs.time }}"
-        id: run_tests
       
       - name: Gather relevant data for e2e testim tests
         id: gather_data
@@ -299,85 +295,113 @@ jobs:
           echo '::set-output name=namespace::'$NAMESPACE
           echo '::set-output name=deployment_name::'$DEPLOYMENT_NAME
 
-  # run-e2e-test:
-  #   needs: deploy
-  #   if: ${{ needs.deploy.outputs.environment == 'staging' && needs.deploy.outputs.run_e2e_tests == 'true' }}
-  #   name: run end to end tests
-  #   runs-on: stable-runners
-  #   permissions:
-  #     contents: "read"
-  #     id-token: "write"
-  #   steps:
-  #     - uses: actions/checkout@v3
-  #       with:
-  #         fetch-depth: 0
+  run-e2e-test:
+    needs: deploy
+    if: ${{ needs.deploy.outputs.environment == 'staging' && needs.deploy.outputs.run_e2e_tests == 'true' }}
+    name: run end to end tests
+    runs-on: stable-runners
+    permissions:
+      contents: "read"
+      id-token: "write"
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
       
-  #     - uses: actions/setup-node@v3
-  #       with:
-  #         node-version: '16.13.0'
+      - uses: actions/setup-node@v3
+        with:
+          node-version: '16.13.0'
 
-  #     - id: "auth"
-  #       name: "Authenticate to Google Cloud"
-  #       uses: "google-github-actions/auth@v0"
-  #       with:
-  #         token_format: "access_token"
-  #         workload_identity_provider: ${{ secrets.STAGING_GKE_WIP }}
-  #         service_account: ${{ secrets.STAGING_GKE_SA }}
+      - id: "auth"
+        name: "Authenticate to Google Cloud"
+        uses: "google-github-actions/auth@v0"
+        with:
+          token_format: "access_token"
+          workload_identity_provider: ${{ secrets.STAGING_GKE_WIP }}
+          service_account: ${{ secrets.STAGING_GKE_SA }}
 
-  #     - id: 'get-credentials'
-  #       uses: 'google-github-actions/get-gke-credentials@v0'
-  #       with:
-  #         cluster_name: ${{ env.STAGING_CLUSTER_NAME }}
-  #         location: ${{ env.STAGING_CLUSTER_LOCATION }}
+      - id: 'get-credentials'
+        uses: 'google-github-actions/get-gke-credentials@v0'
+        with:
+          cluster_name: ${{ env.STAGING_CLUSTER_NAME }}
+          location: ${{ env.STAGING_CLUSTER_LOCATION }}
 
-  #     - uses: azure/setup-kubectl@v3
-  #       id: install
+      - uses: azure/setup-kubectl@v3
+        id: install
       
-  #     # - id: "check_status"
-  #     #   name: "Check deployment status in cluster"
-  #     #   run: |-
-  #     #     echo "Next line is max status tries"
-  #     #     echo $MAX_STATUS_TRIES
-  #     #     NEXT_WAIT_TIME=0;while [[ $(kubectl get deployment $DEPLOYMENT_NAME -n $NAMESPACE -o jsonpath="{.status.conditions[0].status}")=="False" ]] && [[ $NEXT_WAIT_TIME -lt $MAX_STATUS_TRIES ]];do echo $NEXT_WAIT_TIME;sleep $(( NEXT_WAIT_TIME++ ));done;
-  #     #     FINAL_STATUS=$(kubectl get deployment $DEPLOYMENT_NAME -n $NAMESPACE -o jsonpath="{.status.conditions[0].status}")
-  #     #     echo "Status of deployment is $FINAL_STATUS"
-  #     #     echo '::set-output name=final_status::'$FINAL_STATUS
-  #     #   env:
-  #     #     NAMESPACE: ${{needs.deploy.outputs.namespace}}
-  #     #     DEPLOYMENT_NAME: ${{needs.deploy.outputs.deployment_name}}
+      # - id: "check_status"
+      #   name: "Check deployment status in cluster"
+      #   run: |-
+      #     echo "Next line is max status tries"
+      #     echo $MAX_STATUS_TRIES
+      #     NEXT_WAIT_TIME=0;while [[ $(kubectl get deployment $DEPLOYMENT_NAME -n $NAMESPACE -o jsonpath="{.status.conditions[0].status}")=="False" ]] && [[ $NEXT_WAIT_TIME -lt $MAX_STATUS_TRIES ]];do echo $NEXT_WAIT_TIME;sleep $(( NEXT_WAIT_TIME++ ));done;
+      #     FINAL_STATUS=$(kubectl get deployment $DEPLOYMENT_NAME -n $NAMESPACE -o jsonpath="{.status.conditions[0].status}")
+      #     echo "Status of deployment is $FINAL_STATUS"
+      #     echo '::set-output name=final_status::'$FINAL_STATUS
+      #   env:
+      #     NAMESPACE: ${{needs.deploy.outputs.namespace}}
+      #     DEPLOYMENT_NAME: ${{needs.deploy.outputs.deployment_name}}
       
-  #     - id: run_testim
-  #       name: Run testim e2e test if deployment is true
-  #       # if: ${{ env.FINAL_STATUS == 'True'}}
-  #       continue-on-error: true
-  #       run: |-
-  #         npm i -g @testim/testim-cli && testim --token ${{ secrets.TESTIM_API_TOKEN }} --project $TESTIM_PROJECT --grid $TESTIM_GRID --suite $TESTIM_SUITE $TESTIM_ADDITIONAL_FLAGS
-  #       env:
-  #         FINAL_STATUS: ${{ steps.check_status.outputs.final_status }}
+      # - id: run_testim
+      #   name: Run testim e2e test if deployment is true
+      #   if: ${{ env.FINAL_STATUS == 'True'}}
+      #   continue-on-error: true
+      #   run: |-
+      #     npm i -g @testim/testim-cli && testim --token ${{ secrets.TESTIM_API_TOKEN }} --project $TESTIM_PROJECT --grid $TESTIM_GRID --suite $TESTIM_SUITE $TESTIM_ADDITIONAL_FLAGS
+      #   env:
+      #     FINAL_STATUS: ${{ steps.check_status.outputs.final_status }}
 
-  #     - name: Slack Notification for testim failure
-  #       id: slack_testim_notif
-  #       if: steps.run_testim.outcome == 'failure'
-  #       uses: slackapi/slack-github-action@v1.19.0
-  #       with:
-  #         payload: "{\"text\":\"Testim result\", \"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Testim failed! Please check `${{ env.TESTIM_SUITE }}` suite on https://app.testim.io/#/project/${{ env.TESTIM_PROJECT }}/branch/master/runs/suites\"}}]}"
-  #       env:
-  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-  #         SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+      - name: Slack Notification for testim failure
+        id: slack_testim_notif_failure
+        # if: steps.run_testim.outcome == 'failure'
+        uses: slackapi/slack-github-action@v1.23.0
+        with:
+          channel-id: '#plt-239'
+          payload: |-
+            {
+              "text": "Testim failed",
+              "thread_ts": "${{ needs.deploy.outputs.thread_ts }}",
+              "blocks": [
+                {
+                  "type": "section",
+                  "text": {
+                    "type": "mrkdwn",
+                    "text": "Testim failed! Please check `${{ env.TESTIM_SUITE }}` suite on https://app.testim.io/#/project/${{ env.TESTIM_PROJECT }}/branch/master/runs/suites "
+                  }
+                }
+              ]
+            }
+        env:
+          SLACK_BOT_TOKEN: ${{ secrets.SLACK_GITHUB_BOT_TOKEN }}
 
-  #     - name: Fail workflow if testim fails
-  #       id: fail_wf_testim
-  #       if: steps.run_testim.outcome == 'failure'
-  #       run: |-
-  #         echo "Testim failed! Please check ${{ env.TESTIM_SUITE }} suite on https://app.testim.io/#/project/${{ env.TESTIM_PROJECT }}/branch/master/runs/suites"
-  #         exit 1
-      
-  #     - name: Slack Notification for testim success
-  #       id: slack_testim_notif_success
-  #       if: steps.run_testim.outcome == 'success'
-  #       uses: slackapi/slack-github-action@v1.19.0
-  #       with:
-  #         payload: "{\"text\":\"Testim result\", \"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Testim succeded! Please check `${{ env.TESTIM_SUITE }}` suite on https://app.testim.io/#/project/${{ env.TESTIM_PROJECT }}/branch/master/runs/suites for more details\"}}]}"
-  #       env:
-  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-  #         SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+      - name: Slack Notification for testim failure
+        id: slack_testim_notif_success
+        # if: steps.run_testim.outcome == 'failure'
+        uses: slackapi/slack-github-action@v1.23.0
+        with:
+          channel-id: '#plt-239'
+          payload: |-
+            {
+              "text": "Testim succeded",
+              "thread_ts": "${{ needs.deploy.outputs.thread_ts }}",
+              "blocks": [
+                {
+                  "type": "section",
+                  "text": {
+                    "type": "mrkdwn",
+                    "text": "Testim succeded! Please check `${{ env.TESTIM_SUITE }}` suite on https://app.testim.io/#/project/${{ env.TESTIM_PROJECT }}/branch/master/runs/suites for more details "
+                  }
+                }
+              ]
+            }
+        env:
+          SLACK_BOT_TOKEN: ${{ secrets.SLACK_GITHUB_BOT_TOKEN }}
+
+
+
+      # - name: Fail workflow if testim fails
+      #   id: fail_wf_testim
+      #   if: steps.run_testim.outcome == 'failure'
+      #   run: |-
+      #     echo "Testim failed! Please check ${{ env.TESTIM_SUITE }} suite on https://app.testim.io/#/project/${{ env.TESTIM_PROJECT }}/branch/master/runs/suites"
+      #     exit 1
