feat(platform): PLT-239 add testim OPTIONAL e2e test in case of deploying to stage (#9)
Add testim OPTIONAL e2e test in case of deploying to stage

diff --git a/.github/workflows/manual-deploy.yml b/.github/workflows/manual-deploy.yml
--- a/.github/workflows/manual-deploy.yml
+++ b/.github/workflows/manual-deploy.yml
@@ -27,6 +27,42 @@ on:
           required: true
           type: string
           description: "Owner and repo name containing your k8s manifests - like ultimateai/k8s-manifests"
+        run_e2e_tests:
+          required: false
+          type: string
+          description: "Wether to execute or not e2e tests - if yes, staging cluster name, testim_project, testim_grid and testim_suite must be provided"
+          default: "false"
+        staging_cluster_name:
+          required: false
+          type: string
+          description: "Cluster name of stage environment, where e2e test will be run"
+        staging_cluster_location:
+          required: false
+          type: string
+          description: "Location of cluster in stage environment"
+        testim_project:
+          required: false
+          type: string
+          description: "Testim project ID"
+        testim_grid:
+          required: false
+          type: string
+          description: "Testim grid"
+        testim_suite:
+          required: false
+          type: string
+          description: "Testim suite"
+        testim_additional_flags:
+          required: false 
+          type: string
+          description: "Additional flags for testim cli (--turbo-mode --parallel 2)"
+        max_status_tries:
+          required: false 
+          type: number
+          description: "Marks increasing wait time for step checking deployment status"
+          default: 12
+        
+        
 
 
 env:
@@ -36,12 +72,25 @@ env:
   GITHUB_EMAIL: ${{ inputs.github_email }}
   GITHUB_USER: ${{ inputs.github_user }}
   K8S_MANIFESTS_REPO: ${{ inputs.k8s_manifests_repo }}
+  RUN_E2E_TESTS: ${{ inputs.run_e2e_tests }}
+  STAGING_CLUSTER_NAME: ${{ inputs.staging_cluster_name }}
+  STAGING_CLUSTER_LOCATION: ${{ inputs.staging_cluster_location }}
+  TESTIM_PROJECT: ${{ inputs.testim_project }}
+  TESTIM_GRID: ${{ inputs.testim_grid }}
+  TESTIM_SUITE: ${{ inputs.testim_suite }}
+  TESTIM_ADDITIONAL_FLAGS: ${{ inputs.testim_additional_flags }}
+  MAX_STATUS_TRIES: ${{ inputs.max_status_tries }}
 
 
 jobs:
   deploy:
     name: Update k8s-manifest repo
     runs-on: self-hosted
+    outputs: 
+      namespace: ${{ steps.gather_data.outputs.namespace }}
+      deployment_name: ${{ steps.gather_data.outputs.deployment_name }}
+      environment: ${{ env.ENVIRONMENT}}
+      run_e2e_tests: ${{ env.RUN_E2E_TESTS}}
     permissions:
       contents: "read"
       id-token: "write"
@@ -50,7 +99,6 @@ jobs:
         with:
           fetch-depth: 0
           
-
       - id: "image_name"
         name: "Get repo name and update IMAGE_NAME"
         run: |- 
@@ -131,7 +179,95 @@ jobs:
           OLD_VERSION: ${{ steps.get_old_version.outputs.old_version }}
           RELEASE_TITLE: ${{ steps.fetch_latest_release.outputs.name }}
           CHANGELOG_LINES: ${{ steps.get_changelog_content.outputs.changelog_lines }}
-
-                  
-
       
+      - name: Gather relevant data for e2e testim tests
+        id: gather_data
+        if: ${{ (env.ENVIRONMENT == 'staging') && (1==1) }} 
+        run: |-
+          NAMESPACE=$(cat $APP_SQUAD/${{ github.event.repository.name }}/overlay/$ENVIRONMENT/kustomization.yaml | yq .namespace)
+          DEPLOYMENT_NAME=$(echo $(cat $APP_SQUAD/${{ github.event.repository.name }}/overlay/$ENVIRONMENT/kustomization.yaml | yq .namePrefix)deployment)
+          echo '::set-output name=namespace::'$NAMESPACE
+          echo '::set-output name=deployment_name::'$DEPLOYMENT_NAME
+
+  run-e2e-test:
+    needs: deploy
+    if: ${{ needs.deploy.outputs.environment == 'staging' && needs.deploy.outputs.run_e2e_tests == 'true' }}
+    name: run end to end tests
+    runs-on: self-hosted
+    permissions:
+      contents: "read"
+      id-token: "write"
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+      
+      - uses: actions/setup-node@v2
+        with:
+          node-version: '16.13.0'
+
+      - id: "auth"
+        name: "Authenticate to Google Cloud"
+        uses: "google-github-actions/auth@v0"
+        with:
+          token_format: "access_token"
+          workload_identity_provider: ${{ secrets.STAGING_GKE_WIP }}
+          service_account: ${{ secrets.STAGING_GKE_SA }}
+
+      - id: 'get-credentials'
+        uses: 'google-github-actions/get-gke-credentials@v0'
+        with:
+          cluster_name: ${{ env.STAGING_CLUSTER_NAME }}
+          location: ${{ env.STAGING_CLUSTER_LOCATION }}
+
+      - uses: azure/setup-kubectl@v3
+        id: install
+      
+      - id: "check_status"
+        name: "Check deployment status in cluster"
+        run: |-
+          echo "Next line is max status tries"
+          echo $MAX_STATUS_TRIES
+          NEXT_WAIT_TIME=0;while [[ $(kubectl get deployment $DEPLOYMENT_NAME -n $NAMESPACE -o jsonpath="{.status.conditions[0].status}")=="False" ]] && [[ $NEXT_WAIT_TIME -lt $MAX_STATUS_TRIES ]];do echo $NEXT_WAIT_TIME;sleep $(( NEXT_WAIT_TIME++ ));done;
+          FINAL_STATUS=$(kubectl get deployment $DEPLOYMENT_NAME -n $NAMESPACE -o jsonpath="{.status.conditions[0].status}")
+          echo "Status of deployment is $FINAL_STATUS"
+          echo '::set-output name=final_status::'$FINAL_STATUS
+        env:
+          NAMESPACE: ${{needs.deploy.outputs.namespace}}
+          DEPLOYMENT_NAME: ${{needs.deploy.outputs.deployment_name}}
+      
+      - id: run_testim
+        name: Run testim e2e test if deployment is true
+        if: ${{ env.FINAL_STATUS == 'True'}}
+        continue-on-error: true
+        run: |-
+          npm i -g @testim/testim-cli && testim --token ${{ secrets.TESTIM_API_TOKEN }} --project $TESTIM_PROJECT --grid $TESTIM_GRID --suite $TESTIM_SUITE $TESTIM_ADDITIONAL_FLAGS
+        env:
+          FINAL_STATUS: ${{ steps.check_status.outputs.final_status }}
+
+      - name: Slack Notification for testim failure
+        id: slack_testim_notif
+        if: steps.run_testim.outcome == 'failure'
+        uses: slackapi/slack-github-action@v1.19.0
+        with:
+          payload: "{\"text\":\"Testim result\", \"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Testim failed! Please check `${{ env.TESTIM_SUITE }}` suite on https://app.testim.io/#/project/${{ env.TESTIM_PROJECT }}/branch/master/runs/suites\"}}]}"
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+
+      - name: Fail workflow if testim fails
+        id: fail_wf_testim
+        if: steps.run_testim.outcome == 'failure'
+        run: |-
+          echo "Testim failed! Please check ${{ env.TESTIM_SUITE }} suite on https://app.testim.io/#/project/${{ env.TESTIM_PROJECT }}/branch/master/runs/suites"
+          exit 1
+      
+      - name: Slack Notification for testim success
+        id: slack_testim_notif_success
+        if: steps.run_testim.outcome == 'success'
+        uses: slackapi/slack-github-action@v1.19.0
+        with:
+          payload: "{\"text\":\"Testim result\", \"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Testim succeded! Please check `${{ env.TESTIM_SUITE }}` suite on https://app.testim.io/#/project/${{ env.TESTIM_PROJECT }}/branch/master/runs/suites for more details\"}}]}"
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
