First attempt

diff --git a/.github/workflows/manual-deploy.yml b/.github/workflows/manual-deploy.yml
--- a/.github/workflows/manual-deploy.yml
+++ b/.github/workflows/manual-deploy.yml
@@ -200,43 +200,43 @@ jobs:
         env:
           TAGS: ${{ steps.tag_to_deploy.outputs.tag }}
           
-      # - name: Update the Image tags and env files for Selected Environment
-      #   run: |-
-      #     if [[ $APP_NAMES == *","* ]]; then
-      #       IFS=',' read -r -a array_app_names <<< "$APP_NAMES"
-      #       for app_name in "${array_app_names[@]}"
-      #       do
-      #         if [[ -f "$HOME/commonfile.env" ]]; then
-      #           cat $HOME/$app_name-commonfile.env > $APP_SQUAD/$app_name/base/base.env
-      #         fi
-      #         cd $APP_SQUAD/$app_name/overlay/$ENVIRONMENT
-      #         FILE_ENV=$(ls | grep ".env");cat $HOME/$app_name-envfile.env > $FILE_ENV
-      #         kustomize edit set image app=${IMAGE_NAME}:${TAGS}
-      #         cat kustomization.yaml
-      #         git config --local user.email $GITHUB_EMAIL
-      #         git config --local user.name $GITHUB_USER
-      #         git commit -m "update $app_name image to ${IMAGE_NAME}:${TAGS}" -a
-      #         git push ${REMOTE_REPO} HEAD:main --force 
-      #         cd ../../../../
-      #       done 
-      #     else
-      #       if [[ -f "$HOME/commonfile.env" ]]; then
-      #         cat $HOME/commonfile.env > $APP_SQUAD/${APP_NAMES}/base/base.env
-      #       fi
-      #       cd $APP_SQUAD/${APP_NAMES}/overlay/$ENVIRONMENT
-      #       FILE_ENV=$(ls | grep ".env");cat $HOME/envfile.env > $FILE_ENV
-      #       kustomize edit set image app=${IMAGE_NAME}:${TAGS}
-      #       cat kustomization.yaml
-      #       git config --local user.email $GITHUB_EMAIL
-      #       git config --local user.name $GITHUB_USER
-      #       git commit -m "update image to ${IMAGE_NAME}:${TAGS}" -a
-      #       git push ${REMOTE_REPO} HEAD:main --force 
-      #     fi
-      #   env:
-      #     TAGS: ${{ steps.tag_to_deploy.outputs.tag }}
-      #     REMOTE_REPO: https://${{ secrets.ULTIMATE_GITHUB_PAT }}@github.com/${{ env.K8S_MANIFESTS_REPO }}.git
-      #     IMAGE_NAME: ${{ steps.image_name.outputs.image_name }}
-      #     APP_NAMES: ${{ steps.app_names.outputs.app_names }}
+      - name: Update the Image tags and env files for Selected Environment
+        run: |-
+          if [[ $APP_NAMES == *","* ]]; then
+            IFS=',' read -r -a array_app_names <<< "$APP_NAMES"
+            for app_name in "${array_app_names[@]}"
+            do
+              if [[ -f "$HOME/commonfile.env" ]]; then
+                cat $HOME/$app_name-commonfile.env > $APP_SQUAD/$app_name/base/base.env
+              fi
+              cd $APP_SQUAD/$app_name/overlay/$ENVIRONMENT
+              FILE_ENV=$(ls | grep ".env");cat $HOME/$app_name-envfile.env > $FILE_ENV
+              kustomize edit set image app=${IMAGE_NAME}:${TAGS}
+              cat kustomization.yaml
+              git config --local user.email $GITHUB_EMAIL
+              git config --local user.name $GITHUB_USER
+              git commit -m "update $app_name image to ${IMAGE_NAME}:${TAGS}" -a
+              git push ${REMOTE_REPO} HEAD:main --force 
+              cd ../../../../
+            done 
+          else
+            if [[ -f "$HOME/commonfile.env" ]]; then
+              cat $HOME/commonfile.env > $APP_SQUAD/${APP_NAMES}/base/base.env
+            fi
+            cd $APP_SQUAD/${APP_NAMES}/overlay/$ENVIRONMENT
+            FILE_ENV=$(ls | grep ".env");cat $HOME/envfile.env > $FILE_ENV
+            kustomize edit set image app=${IMAGE_NAME}:${TAGS}
+            cat kustomization.yaml
+            git config --local user.email $GITHUB_EMAIL
+            git config --local user.name $GITHUB_USER
+            git commit -m "update image to ${IMAGE_NAME}:${TAGS}" -a
+            git push ${REMOTE_REPO} HEAD:main --force 
+          fi
+        env:
+          TAGS: ${{ steps.tag_to_deploy.outputs.tag }}
+          REMOTE_REPO: https://${{ secrets.ULTIMATE_GITHUB_PAT }}@github.com/${{ env.K8S_MANIFESTS_REPO }}.git
+          IMAGE_NAME: ${{ steps.image_name.outputs.image_name }}
+          APP_NAMES: ${{ steps.app_names.outputs.app_names }}
 
       - uses: slackapi/slack-github-action@v1.23.0
         name: Slack notification
@@ -298,7 +298,7 @@ jobs:
       
       - name: Gather relevant data for e2e testim tests
         id: gather_data
-        if: ${{ (env.ENVIRONMENT == 'staging') && (1==1) }} 
+        if: ${{ (env.ENVIRONMENT == 'staging') && (env.RUN_E2E_TESTS == 'true') }} 
         run: |-
           NAMESPACE=$(cat $APP_SQUAD/${{ github.event.repository.name }}/overlay/$ENVIRONMENT/kustomization.yaml | yq .namespace)
           DEPLOYMENT_NAME=$(echo $(cat $APP_SQUAD/${{ github.event.repository.name }}/overlay/$ENVIRONMENT/kustomization.yaml | yq .namePrefix)deployment)
@@ -339,31 +339,31 @@ jobs:
       - uses: azure/setup-kubectl@v3
         id: install
       
-      # - id: "check_status"
-      #   name: "Check deployment status in cluster"
-      #   run: |-
-      #     echo "Next line is max status tries"
-      #     echo $MAX_STATUS_TRIES
-      #     NEXT_WAIT_TIME=0;while [[ $(kubectl get deployment $DEPLOYMENT_NAME -n $NAMESPACE -o jsonpath="{.status.conditions[0].status}")=="False" ]] && [[ $NEXT_WAIT_TIME -lt $MAX_STATUS_TRIES ]];do echo $NEXT_WAIT_TIME;sleep $(( NEXT_WAIT_TIME++ ));done;
-      #     FINAL_STATUS=$(kubectl get deployment $DEPLOYMENT_NAME -n $NAMESPACE -o jsonpath="{.status.conditions[0].status}")
-      #     echo "Status of deployment is $FINAL_STATUS"
-      #     echo '::set-output name=final_status::'$FINAL_STATUS
-      #   env:
-      #     NAMESPACE: ${{needs.deploy.outputs.namespace}}
-      #     DEPLOYMENT_NAME: ${{needs.deploy.outputs.deployment_name}}
+      - id: "check_status"
+        name: "Check deployment status in cluster"
+        run: |-
+          echo "Next line is max status tries"
+          echo $MAX_STATUS_TRIES
+          NEXT_WAIT_TIME=0;while [[ $(kubectl get deployment $DEPLOYMENT_NAME -n $NAMESPACE -o jsonpath="{.status.conditions[0].status}")=="False" ]] && [[ $NEXT_WAIT_TIME -lt $MAX_STATUS_TRIES ]];do echo $NEXT_WAIT_TIME;sleep $(( NEXT_WAIT_TIME++ ));done;
+          FINAL_STATUS=$(kubectl get deployment $DEPLOYMENT_NAME -n $NAMESPACE -o jsonpath="{.status.conditions[0].status}")
+          echo "Status of deployment is $FINAL_STATUS"
+          echo '::set-output name=final_status::'$FINAL_STATUS
+        env:
+          NAMESPACE: ${{needs.deploy.outputs.namespace}}
+          DEPLOYMENT_NAME: ${{needs.deploy.outputs.deployment_name}}
       
-      # - id: run_testim
-      #   name: Run testim e2e test if deployment is true
-      #   # if: ${{ env.FINAL_STATUS == 'True'}}
-      #   continue-on-error: true
-      #   run: |-
-      #     npm i -g @testim/testim-cli && testim --token ${{ secrets.TESTIM_API_TOKEN }} --project $TESTIM_PROJECT --grid $TESTIM_GRID --suite $TESTIM_SUITE $TESTIM_ADDITIONAL_FLAGS
-      #   env:
-      #     FINAL_STATUS: ${{ steps.check_status.outputs.final_status }}
+      - id: run_testim
+        name: Run testim e2e test if deployment is true
+        # if: ${{ env.FINAL_STATUS == 'True'}}
+        continue-on-error: true
+        run: |-
+          npm i -g @testim/testim-cli && testim --token ${{ secrets.TESTIM_API_TOKEN }} --project $TESTIM_PROJECT --grid $TESTIM_GRID --suite $TESTIM_SUITE $TESTIM_ADDITIONAL_FLAGS
+        env:
+          FINAL_STATUS: ${{ steps.check_status.outputs.final_status }}
 
       - name: Slack Notification for testim failure
         id: slack_testim_notif_failure
-        # if: steps.run_testim.outcome == 'failure'
+        if: steps.run_testim.outcome == 'failure'
         uses: slackapi/slack-github-action@v1.23.0
         with:
           channel-id: ${{ env.SLACK_CHANNEL_ID }}
@@ -384,16 +384,16 @@ jobs:
         env:
           SLACK_BOT_TOKEN: ${{ secrets.SLACK_GITHUB_BOT_TOKEN }}
 
-      # - name: Fail workflow if testim fails
-      #   id: fail_wf_testim
-      #   if: steps.run_testim.outcome == 'failure'
-      #   run: |-
-      #     echo "Testim failed! Please check ${{ env.TESTIM_SUITE }} suite on https://app.testim.io/#/project/${{ env.TESTIM_PROJECT }}/branch/master/runs/suites"
-      #     exit 1
+      - name: Fail workflow if testim fails
+        id: fail_wf_testim
+        if: steps.run_testim.outcome == 'failure'
+        run: |-
+          echo "Testim failed! Please check ${{ env.TESTIM_SUITE }} suite on https://app.testim.io/#/project/${{ env.TESTIM_PROJECT }}/branch/master/runs/suites"
+          exit 1
 
-      - name: Slack Notification for testim failure
+      - name: Slack Notification for testim success
         id: slack_testim_notif_success
-        # if: steps.run_testim.outcome == 'success'
+        if: steps.run_testim.outcome == 'success'
         uses: slackapi/slack-github-action@v1.23.0
         with:
           channel-id: ${{ env.SLACK_CHANNEL_ID }}
