feat: PLT-000 (#29)
* Pedro's fixes

* Test testim slack

* Test testim slack

* Test testim slack

diff --git a/.github/workflows/manual-deploy.yml b/.github/workflows/manual-deploy.yml
--- a/.github/workflows/manual-deploy.yml
+++ b/.github/workflows/manual-deploy.yml
@@ -245,7 +245,7 @@ jobs:
               cat kustomization.yaml
               git config --local user.email $GITHUB_EMAIL
               git config --local user.name $GITHUB_USER
-              git commit -m "update $app_name image to ${IMAGE_NAME}:${TAGS}" -a || echo "nothing to commit"
+              git commit -m "update $app_name image to ${IMAGE_NAME}:${TAGS}" -a || echo "Nothing to commit, $app_name version ${TAGS} is already deployed to $ENVIRONMENT" >> $GITHUB_STEP_SUMMARY
               git push ${REMOTE_REPO} HEAD:main --force 
               cd ../../../../
             done 
@@ -256,7 +256,7 @@ jobs:
             cat kustomization.yaml
             git config --local user.email $GITHUB_EMAIL
             git config --local user.name $GITHUB_USER
-            git commit -m "update image to ${IMAGE_NAME}:${TAGS}" -a || echo "nothing to commit"
+            git commit -m "update image to ${IMAGE_NAME}:${TAGS}" -a || echo "Nothing to commit, version ${TAGS} is already deployed to $ENVIRONMENT" >> $GITHUB_STEP_SUMMARY
             git push ${REMOTE_REPO} HEAD:main --force 
           fi
         env:
@@ -268,7 +268,7 @@ jobs:
       - uses: slackapi/slack-github-action@v1.23.0
         name: Slack notification
         id: slack_notif
-        if: ${{ (env.ENVIRONMENT == 'production') || ((env.ENVIRONMENT == 'staging') && (env.RUN_E2E_TESTS == 'true')) }} 
+        if: ${{ env.ENVIRONMENT == 'production' }} 
         with:
           channel-id: ${{ env.SLACK_CHANNEL_ID }}
           payload: |-
@@ -293,7 +293,7 @@ jobs:
 
       - uses: slackapi/slack-github-action@v1.23.0
         name: Threaded slack notification for version comparison
-        if: ${{ (env.ENVIRONMENT == 'production') || ((env.ENVIRONMENT == 'staging') && (env.RUN_E2E_TESTS == 'true')) }} 
+        if: ${{ env.ENVIRONMENT == 'production' }} 
         id: slack_threaded_version
         with:
           channel-id: ${{ env.SLACK_CHANNEL_ID }}
@@ -322,9 +322,15 @@ jobs:
         if: ${{ (env.ENVIRONMENT == 'staging') && (env.RUN_E2E_TESTS == 'true') }} 
         run: |-
           NAMESPACE=$(cat $APP_SQUAD/${{ github.event.repository.name }}/overlay/$ENVIRONMENT/kustomization.yaml | yq .namespace)
-          DEPLOYMENT_NAME=$(echo $(cat $APP_SQUAD/${{ github.event.repository.name }}/overlay/$ENVIRONMENT/kustomization.yaml | yq .namePrefix)deployment)
+          if [[ -z "${SINGLE_APP_NAME}" ]]; then
+            DEPLOYMENT_NAME=$(echo $(cat $APP_SQUAD/${{ github.event.repository.name }}/overlay/$ENVIRONMENT/kustomization.yaml | yq .namePrefix)deployment)
+          else
+            DEPLOYMENT_NAME=$(echo $(cat $APP_SQUAD/$SINGLE_APP_NAME/overlay/$ENVIRONMENT/kustomization.yaml | yq .namePrefix)deployment)
+          fi
           echo "namespace=$NAMESPACE" >> $GITHUB_OUTPUT
           echo "deployment_name=$DEPLOYMENT_NAME" >> $GITHUB_OUTPUT
+        env:
+          SINGLE_APP_NAME: ${{ steps.app_names.outputs.single_app_name }}
 
   run-e2e-test:
     needs: deploy
@@ -343,44 +349,66 @@ jobs:
         with:
           node-version: '16.13.0'
 
-      - id: "auth"
-        name: "Authenticate to Google Cloud"
-        uses: "google-github-actions/auth@v0"
-        with:
-          token_format: "access_token"
-          workload_identity_provider: ${{ secrets.STAGING_GKE_WIP }}
-          service_account: ${{ secrets.STAGING_GKE_SA }}
+      # This just makes no sense at all - deployments with new version can take up to five minutes to show. 
+      # - id: "auth"
+      #   name: "Authenticate to Google Cloud"
+      #   uses: "google-github-actions/auth@v1"
+      #   with:
+      #     token_format: "access_token"
+      #     workload_identity_provider: ${{ secrets.STAGING_GKE_WIP }}
+      #     service_account: ${{ secrets.STAGING_GKE_SA }}
 
-      - id: 'get-credentials'
-        uses: 'google-github-actions/get-gke-credentials@v0'
-        with:
-          cluster_name: ${{ env.STAGING_CLUSTER_NAME }}
-          location: ${{ env.STAGING_CLUSTER_LOCATION }}
+      # - id: 'get-credentials'
+      #   uses: 'google-github-actions/get-gke-credentials@v1'
+      #   with:
+      #     cluster_name: ${{ env.STAGING_CLUSTER_NAME }}
+      #     location: ${{ env.STAGING_CLUSTER_LOCATION }}
 
-      - uses: azure/setup-kubectl@v3
-        id: install
+      # - uses: azure/setup-kubectl@v3
+      #   id: install
       
-      - id: "check_status"
-        name: "Check deployment status in cluster"
-        run: |-
-          echo "Next line is max status tries"
-          echo $MAX_STATUS_TRIES
-          NEXT_WAIT_TIME=0;while [[ $(kubectl get deployment $DEPLOYMENT_NAME -n $NAMESPACE -o jsonpath="{.status.conditions[0].status}")=="False" ]] && [[ $NEXT_WAIT_TIME -lt $MAX_STATUS_TRIES ]];do echo $NEXT_WAIT_TIME;sleep $(( NEXT_WAIT_TIME++ ));done;
-          FINAL_STATUS=$(kubectl get deployment $DEPLOYMENT_NAME -n $NAMESPACE -o jsonpath="{.status.conditions[0].status}")
-          echo "Status of deployment is $FINAL_STATUS"
-          echo "final_status=$FINAL_STATUS" >> $GITHUB_OUTPUT  
-        env:
-          NAMESPACE: ${{needs.deploy.outputs.namespace}}
-          DEPLOYMENT_NAME: ${{needs.deploy.outputs.deployment_name}}
+      # - id: "check_status"
+      #   name: "Check deployment status in cluster"
+      #   run: |-
+      #     echo "Next line is max status tries"
+      #     echo $MAX_STATUS_TRIES
+      #     NEXT_WAIT_TIME=0;while [[ $(kubectl get deployment $DEPLOYMENT_NAME -n $NAMESPACE -o jsonpath="{.status.conditions[0].status}")=="False" ]] && [[ $NEXT_WAIT_TIME -lt $MAX_STATUS_TRIES ]];do echo $NEXT_WAIT_TIME;sleep $(( NEXT_WAIT_TIME++ ));done;
+      #     FINAL_STATUS=$(kubectl get deployment $DEPLOYMENT_NAME -n $NAMESPACE -o jsonpath="{.status.conditions[0].status}")
+      #     echo "Status of deployment is $FINAL_STATUS"
+      #     echo "final_status=$FINAL_STATUS" >> $GITHUB_OUTPUT  
+      #   env:
+      #     NAMESPACE: ${{needs.deploy.outputs.namespace}}
+      #     DEPLOYMENT_NAME: ${{needs.deploy.outputs.deployment_name}}
       
       - id: run_testim
-        name: Run testim e2e test if deployment is true
+        name: Run testim e2e test suite
         # if: ${{ env.FINAL_STATUS == 'True'}}
         continue-on-error: true
         run: |-
           npm i -g @testim/testim-cli && testim --token ${{ secrets.TESTIM_API_TOKEN }} --project $TESTIM_PROJECT --grid $TESTIM_GRID --suite $TESTIM_SUITE $TESTIM_ADDITIONAL_FLAGS
         env:
           FINAL_STATUS: ${{ steps.check_status.outputs.final_status }}
+
+      - uses: slackapi/slack-github-action@v1.23.0
+        name: Slack notification
+        id: slack_notif_testim
+        with:
+          channel-id: ${{ env.SLACK_CHANNEL_ID }}
+          payload: |-
+            {
+              "text": "Manual deployment",
+              "blocks": [
+                {
+                  "type": "section",
+                  "text": {
+                    "type": "mrkdwn",
+                    "text": "Deployment of `${{ github.event.repository.name }}` to `${{ env.ENVIRONMENT }}` by ${{ github.actor }} - with testim results inside!"
+                  }
+                }
+              ]
+            }
+        env:
+          SLACK_BOT_TOKEN: ${{ secrets.SLACK_GITHUB_BOT_TOKEN }}
 
       - name: Slack Notification for testim failure
         id: slack_testim_notif_failure
@@ -391,7 +419,7 @@ jobs:
           payload: |-
             {
               "text": "Testim failed",
-              "thread_ts": "${{ needs.deploy.outputs.thread_ts }}",
+              "thread_ts": "${{ steps.slack_notif_testim.outputs.thread_ts }}",
               "blocks": [
                 {
                   "type": "section",
@@ -409,7 +437,7 @@ jobs:
         id: fail_wf_testim
         if: steps.run_testim.outcome == 'failure'
         run: |-
-          echo "Testim failed! Please check ${{ env.TESTIM_SUITE }} suite on https://app.testim.io/#/project/${{ env.TESTIM_PROJECT }}/branch/master/runs/suites"
+          echo "Testim failed! Please check ${{ env.TESTIM_SUITE }} suite on https://app.testim.io/#/project/${{ env.TESTIM_PROJECT }}/branch/master/runs/suites" >> $GITHUB_STEP_SUMMARY
           exit 1
 
       - name: Slack Notification for testim success
@@ -421,7 +449,7 @@ jobs:
           payload: |-
             {
               "text": "Testim succeded",
-              "thread_ts": "${{ needs.deploy.outputs.thread_ts }}",
+              "thread_ts": "${{ steps.slack_notif_testim.outputs.thread_ts }}",
               "blocks": [
                 {
                   "type": "section",
