run sonarscan within push image job

diff --git a/.github/workflows/merged-pr.yml b/.github/workflows/merged-pr.yml
--- a/.github/workflows/merged-pr.yml
+++ b/.github/workflows/merged-pr.yml
@@ -374,6 +374,32 @@ jobs:
           TAGS: ${{ steps.fetch_latest_release.outputs.tag_name }}
           IMAGE_NAME: ${{ steps.image_name.outputs.gar_image_name }}
 
+      # Sonarqube steps: check for properties file, if it exist run scan
+      - name: check sonar properties file exists in main branch
+        id: check-properties-file
+        uses: andstor/file-existence-action@v3
+        with:
+          files: "sonar-project.properties"
+
+      # If sonar properties does not exist, fail step
+      - name: Fail the step if sonar properties file does not exist
+        if: steps.check-properties-file.outputs.files_exists == 'false'
+        run: |
+          echo "Sonar properties file does not exist. Please create a sonar-project.properties file in the root of your project." >> $GITHUB_STEP_SUMMARY
+          exit 1
+
+      - name: SonarQube Scan Main
+        if: github.ref == 'refs/heads/main'
+        uses: SonarSource/sonarqube-scan-action@v4.1.0
+        env:
+          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
+          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
+        with:
+          args: >
+            -Dsonar.sourceEncoding=UTF-8
+            -Dsonar.branch.name=main
+            -Dsonar.projectTags=ai-agents
+
       ##Automatic deploy to development on merged PR to main
       - name: "Checkout k8s manifests"
         uses: actions/checkout@v4
